FROM ghcr.io/actions/actions-runner:2.311.0

USER root

# install curl and jq
RUN apt-get update && apt-get install -y curl jq && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# install az cli
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash

# install k3s
RUN curl -sfL https://get.k3s.io | sh -
RUN k3s --version

COPY github-actions-runner/entrypoint.sh ./entrypoint.sh
RUN chmod +x ./entrypoint.sh

USER runner

ENTRYPOINT ["./entrypoint.sh"]
